version: '3'

services:
  api:
   build:
    context: .
    dockerfile: Dockerfile
   volumes:
      - '.:/usr/src/app'
      - /usr/src/app/node_modules
   depends_on:
        - db
   environment:
      NODE_ENV: development
   ports:
      - 4000:4000
   command: npm start
   
  db:
      image: 'mongo:4' 
      ports:
        - "27017:27017"
  adminmongo:
    image: "mrvautin/adminmongo"
    ports:
      - "1234:1234"
    environment:
      - HOST=0.0.0.0
